// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AtlantaCodeCampMobile.Models;
//
//    var speaker = Speaker.FromJson(jsonString);

namespace AtlantaCodeCampMobile.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Speaker
    {
        public static List<Speaker> FromJson(string json) => JsonConvert.DeserializeObject<List<Speaker>>(json, AtlantaCodeCampMobile.Models.Converter.Settings);
    }
}
